FROM oven/bun:1-alpine

WORKDIR /usr/src/app

COPY package.json bun.lock ./

COPY apps/backend/package.json apps/backend/package.json
COPY packages/db/package.json packages/db/package.json

RUN bun install --frozen-lockfile

COPY . .

RUN bun run db:generate

EXPOSE 3000

CMD ["bun", "run","start:backend"]