FROM oven/bun:1-alpine

WORKDIR /usr/src/app

COPY package.json bun.lock ./

COPY apps/web/package.json apps/web/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN bun install --frozen-lockfile

COPY . .

RUN bun run db:generate
RUN bun run build:frontend

EXPOSE 3001

CMD [ "bun", "run", "start:frontend" ]